### ISSUE TITLE
Allow selecting the pixel size of the image being exported 

### ISSUE THREAD

**Issue by lacan** [DBM-MCF/qupath-extension-efficientv2unet#2]
QuPath allows for exporting images and masks at arbitrary resolutions. 
This allows for larger objects to be semgneted as sometimes we do not need the native resolution to get a good segmentation

**Comment by loicsauteur** [comment]
Hi @lacan 
QuPath now exports the images for predictions.
This allows now also predicting in (rectangle) ROIs.
Let me know if you have any further suggestions.
